In [46]:
import pandas as pd
import numpy as np

In [47]:
animalIntakes = pd.read_csv('../data/Austin_Animal_Center_Intakes.csv')

In [48]:
animalIntakes.head()
#len(animalIntakes) #78709

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A748291,*Madison,05/01/2017 02:26:00 PM,05/01/2017 02:26:00 PM,S Pleasant Valley Rd And E Riverside Dr in Aus...,Stray,Normal,Dog,Intact Female,10 months,Pit Bull Mix,Black
1,A750529,NaN,05/28/2017 01:22:00 PM,05/28/2017 01:22:00 PM,8312 North Ih 35 in Austin (TX),Stray,Normal,Dog,Intact Female,5 months,Miniature Schnauzer Mix,White/Cream
2,A730601,NaN,07/07/2016 12:11:00 PM,07/07/2016 12:11:00 PM,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,7 months,Domestic Shorthair Mix,Blue Tabby
3,A748238,NaN,05/01/2017 10:53:00 AM,05/01/2017 10:53:00 AM,Airport Blvd And Oak Springs Dr in Austin (TX),Stray,Normal,Dog,Intact Male,3 years,Bichon Frise Mix,White
4,A683644,*Zoey,07/13/2014 11:02:00 AM,07/13/2014 11:02:00 AM,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,4 weeks,Border Collie Mix,Brown/White

In [49]:
#vagueLocation = animalIntakes[animalIntakes["Found Location"] == "Austin (TX)"]
vagueLocation.head()
#len(vagueLocation) #14109

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
4,A683644,*Zoey,07/13/2014 11:02:00 AM,07/13/2014 11:02:00 AM,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,4 weeks,Border Collie Mix,Brown/White
19,A664571,NaN,10/05/2013 01:43:00 PM,10/05/2013 01:43:00 PM,Austin (TX),Owner Surrender,Normal,Cat,Spayed Female,2 years,Domestic Shorthair Mix,Torbie
23,A724944,Cameron,04/23/2016 11:28:00 AM,04/23/2016 11:28:00 AM,Austin (TX),Owner Surrender,Normal,Cat,Neutered Male,1 year,Domestic Shorthair Mix,Brown Tabby/White
27,A671448,Xander,01/24/2014 02:54:00 PM,01/24/2014 02:54:00 PM,Austin (TX),Public Assist,Normal,Dog,Neutered Male,3 years,Pekingese Mix,Brown/White
38,A758853,Buggs,09/23/2017 09:23:00 AM,09/23/2017 09:23:00 AM,Austin (TX),Owner Surrender,Injured,Dog,Neutered Male,2 years,Chihuahua Longhair Mix,White/Tan

In [50]:
wLocData = animalIntakes[animalIntakes["Found Location"] != "Austin (TX)"]
#len(wLocData) #64600
wLocData.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A748291,*Madison,05/01/2017 02:26:00 PM,05/01/2017 02:26:00 PM,S Pleasant Valley Rd And E Riverside Dr in Aus...,Stray,Normal,Dog,Intact Female,10 months,Pit Bull Mix,Black
1,A750529,NaN,05/28/2017 01:22:00 PM,05/28/2017 01:22:00 PM,8312 North Ih 35 in Austin (TX),Stray,Normal,Dog,Intact Female,5 months,Miniature Schnauzer Mix,White/Cream
2,A730601,NaN,07/07/2016 12:11:00 PM,07/07/2016 12:11:00 PM,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,7 months,Domestic Shorthair Mix,Blue Tabby
3,A748238,NaN,05/01/2017 10:53:00 AM,05/01/2017 10:53:00 AM,Airport Blvd And Oak Springs Dr in Austin (TX),Stray,Normal,Dog,Intact Male,3 years,Bichon Frise Mix,White
5,A676515,Rico,04/11/2014 08:45:00 AM,04/11/2014 08:45:00 AM,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,2 months,Pit Bull Mix,White/Brown

In [51]:
wLocData.describe()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
count,64600,42000,64600,64600,64600,64600,64600,64600,64599,64600,64600,64600
unique,60592,12757,45883,45883,36123,5,8,5,5,46,1905,500
top,A721033,Bella,07/09/2014 12:58:00 PM,07/09/2014 12:58:00 PM,Outside Jurisdiction,Stray,Normal,Dog,Intact Male,1 year,Domestic Shorthair Mix,Black/White
freq,11,243,63,63,912,53776,56159,36116,22112,12046,19402,6657

In [105]:
#len(wLocData[wLocData.DateTime.str.contains("2017")]) #14287
#df[df['A'].str.contains("hello")]

mydat = wLocData[wLocData.DateTime.str.contains("2017")]
#mydat.head(100).MonthYear.sort_values() #full year range confirmed 
mydat.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A748291,*Madison,05/01/2017 02:26:00 PM,05/01/2017 02:26:00 PM,S Pleasant Valley Rd And E Riverside Dr in Aus...,Stray,Normal,Dog,Intact Female,10 months,Pit Bull Mix,Black
1,A750529,NaN,05/28/2017 01:22:00 PM,05/28/2017 01:22:00 PM,8312 North Ih 35 in Austin (TX),Stray,Normal,Dog,Intact Female,5 months,Miniature Schnauzer Mix,White/Cream
3,A748238,NaN,05/01/2017 10:53:00 AM,05/01/2017 10:53:00 AM,Airport Blvd And Oak Springs Dr in Austin (TX),Stray,Normal,Dog,Intact Male,3 years,Bichon Frise Mix,White
12,A756485,NaN,08/20/2017 03:07:00 PM,08/20/2017 03:07:00 PM,1020 Grove Blvd in Austin (TX),Stray,Normal,Cat,Intact Female,1 month,Domestic Shorthair Mix,Blue Tabby
15,A749535,*Bongo,05/16/2017 11:29:00 AM,05/16/2017 11:29:00 AM,6607 S Ih 35 Frontage Rd in Austin (TX),Stray,Normal,Dog,Intact Male,2 years,Border Collie Mix,Black/White

In [106]:
mydat["Found Location"].isnull().sum() #0

0

In [107]:
mydat = mydat.rename(columns = {"Found Location":"FoundLocation"})
mydat.head()

##.str.contains("in Austin (TX)").sum()

,Animal ID,Name,DateTime,MonthYear,FoundLocation,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A748291,*Madison,05/01/2017 02:26:00 PM,05/01/2017 02:26:00 PM,S Pleasant Valley Rd And E Riverside Dr in Aus...,Stray,Normal,Dog,Intact Female,10 months,Pit Bull Mix,Black
1,A750529,NaN,05/28/2017 01:22:00 PM,05/28/2017 01:22:00 PM,8312 North Ih 35 in Austin (TX),Stray,Normal,Dog,Intact Female,5 months,Miniature Schnauzer Mix,White/Cream
3,A748238,NaN,05/01/2017 10:53:00 AM,05/01/2017 10:53:00 AM,Airport Blvd And Oak Springs Dr in Austin (TX),Stray,Normal,Dog,Intact Male,3 years,Bichon Frise Mix,White
12,A756485,NaN,08/20/2017 03:07:00 PM,08/20/2017 03:07:00 PM,1020 Grove Blvd in Austin (TX),Stray,Normal,Cat,Intact Female,1 month,Domestic Shorthair Mix,Blue Tabby
15,A749535,*Bongo,05/16/2017 11:29:00 AM,05/16/2017 11:29:00 AM,6607 S Ih 35 Frontage Rd in Austin (TX),Stray,Normal,Dog,Intact Male,2 years,Border Collie Mix,Black/White

In [108]:
mydat["FoundLocation"] = mydat["FoundLocation"].str.rstrip("in Austin (TX)")
mydat.head()

,Animal ID,Name,DateTime,MonthYear,FoundLocation,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A748291,*Madison,05/01/2017 02:26:00 PM,05/01/2017 02:26:00 PM,S Pleasant Valley Rd And E Riverside Dr,Stray,Normal,Dog,Intact Female,10 months,Pit Bull Mix,Black
1,A750529,NaN,05/28/2017 01:22:00 PM,05/28/2017 01:22:00 PM,8312 North Ih 35,Stray,Normal,Dog,Intact Female,5 months,Miniature Schnauzer Mix,White/Cream
3,A748238,NaN,05/01/2017 10:53:00 AM,05/01/2017 10:53:00 AM,Airport Blvd And Oak Springs Dr,Stray,Normal,Dog,Intact Male,3 years,Bichon Frise Mix,White
12,A756485,NaN,08/20/2017 03:07:00 PM,08/20/2017 03:07:00 PM,1020 Grove Blvd,Stray,Normal,Cat,Intact Female,1 month,Domestic Shorthair Mix,Blue Tabby
15,A749535,*Bongo,05/16/2017 11:29:00 AM,05/16/2017 11:29:00 AM,6607 S Ih 35 Frontage Rd,Stray,Normal,Dog,Intact Male,2 years,Border Collie Mix,Black/White

In [109]:
mydat['city'] = "Austin"
mydat['state'] = "TX"

In [110]:
mydat[mydat['MonthYear'] != mydat['DateTime']].head()

Empty DataFrame
Columns: [Animal ID, Name, DateTime, MonthYear, FoundLocation, Intake Type, Intake Condition, Animal Type, Sex upon Intake, Age upon Intake, Breed, Color, city, state]
Index: []

In [111]:
mydat.columns = ['animal_id','name','date_time','month_year','found_loc','intake_type','intake_condition','animal_type','sex','age','breed','color','city','state']

In [119]:
#mydat = mydat.reset_index()
mydat.head()
mydat = mydat.rename(columns = {"level_0":"index1"})
mydat.head()

,index1,index,animal_id,name,date_time,month_year,found_loc,intake_type,intake_condition,animal_type,sex,age,breed,color,city,state
0,0,0,A748291,*Madison,05/01/2017 02:26:00 PM,05/01/2017 02:26:00 PM,S Pleasant Valley Rd And E Riverside Dr,Stray,Normal,Dog,Intact Female,10 months,Pit Bull Mix,Black,Austin,TX
1,1,1,A750529,NaN,05/28/2017 01:22:00 PM,05/28/2017 01:22:00 PM,8312 North Ih 35,Stray,Normal,Dog,Intact Female,5 months,Miniature Schnauzer Mix,White/Cream,Austin,TX
2,2,3,A748238,NaN,05/01/2017 10:53:00 AM,05/01/2017 10:53:00 AM,Airport Blvd And Oak Springs Dr,Stray,Normal,Dog,Intact Male,3 years,Bichon Frise Mix,White,Austin,TX
3,3,12,A756485,NaN,08/20/2017 03:07:00 PM,08/20/2017 03:07:00 PM,1020 Grove Blvd,Stray,Normal,Cat,Intact Female,1 month,Domestic Shorthair Mix,Blue Tabby,Austin,TX
4,4,15,A749535,*Bongo,05/16/2017 11:29:00 AM,05/16/2017 11:29:00 AM,6607 S Ih 35 Frontage Rd,Stray,Normal,Dog,Intact Male,2 years,Border Collie Mix,Black/White,Austin,TX

In [122]:
mydat.to_csv("../data/Austin_AnimalIntake_addresscleaned.csv")